app.py
from flask import Flask

from blueprints.worlds_blueprint import *
from blueprints.dashboard_blueprint import *
from blueprints.major_wins_blueprint import *
from blueprints.band_results_blueprint import *

app = Flask(__name__)

app.register_blueprint(dashboard)
app.register_blueprint(worlds)
app.register_blueprint(major_wins)
app.register_blueprint(band_results)

if __name__ == "__main__":
    app.run(host="0.0.0.0")

blueprints/band_results_blueprint.py
from flask import Blueprint, render_template, request, jsonify

from modules.generate_data.band_results.band_results import get_bands_list, update_band_data

band_results = Blueprint('band_results', __name__)


@band_results.route('/band_results')
def get_band_results():
    y_list = [2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
    return render_template('band_results.html', data="data", year_list=y_list)


@band_results.route('/_update_band_data')
def update_band_results():
    grade = request.args.get('grade', '1', type=str)
    band = request.args.get('band', '1', type=str)
    year_from = request.args.get('year_from', 2003, type=int)
    year_to = request.args.get('year_to', 2019, type=int)
    compare_band = request.args.get('comp_band', 'none', type=str)
    return jsonify(update_band_data(grade, band, compare_band, year_from, year_to))


@band_results.route('/_get_band_list')
def get_band_list():
    grade = request.args.get('grade', '1', type=str)
    year_from = request.args.get('year_from', 2003, type=int)
    year_to = request.args.get('year_to', 2019, type=int)
    return jsonify(get_bands_list(grade, year_from, year_to))

blueprints/dashboard_blueprint.py
from flask import Blueprint, render_template
import json
import jsonpickle
import plotly

from modules.generate_data.dashboard.perfect_scores import get_perfect_scores
from modules.db.db import *

dashboard = Blueprint('dashboard', __name__)


@dashboard.route('/')
def get_dashboard():
    y_list = [2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
    data = pull_data(helper_collection, {"type": "g1_coc"})
    drumming_data = pull_data(helper_collection, {"type": "g1_drumming_coc"})
    drumming_graphJSON = json.dumps([jsonpickle.decode(drumming_data[0]['data']), y_list],
                                    cls=plotly.utils.PlotlyJSONEncoder)
    graphJSON = json.dumps([jsonpickle.decode(data[0]['data']), y_list], cls=plotly.utils.PlotlyJSONEncoder)
    return render_template('dashboard.html',
                           gs_data=jsonpickle.decode(pull_data(helper_collection, {"type": "slams"})[0]['data']),
                           ps_data=get_perfect_scores(),
                           graphJSON=graphJSON, d_graph_json=drumming_graphJSON,
                           graph_title="Grade One Overall Champion of Champions")

blueprints/major_wins_blueprint.py
from flask import Blueprint, render_template, request
from modules.shared.shared_functions import convert_grade
from modules.generate_data.major_wins.get_results import get_band_results, convert_result_type

major_wins = Blueprint('major_wins', __name__)


@major_wins.route('/major_totals')
def get_major_wins():
    y_list = [2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
    return render_template('major_wins.html', year_list=y_list)


@major_wins.route('/_get_grade_total')
def get_grade_total():
    grade = convert_grade(request.args.get('grade', '1', type=str))
    year_from = request.args.get('year_from', 2003, type=int)
    year_to = request.args.get('year_to', 2019, type=int)
    result_type = request.args.get('type', '1', type=str)
    graph_title = "Total Number of {0} Wins in Grade {1} ({2}-{3})".format(convert_result_type(result_type), grade,
                                                                           year_from, year_to)
    graph_data = get_band_results(str(grade), result_type, year_from, year_to)
    return {'data': graph_data, 'title': graph_title}

blueprints/worlds_blueprint.py
import plotly
import json
from flask import Blueprint, render_template, request, jsonify

from modules.generate_data.worlds.worlds import *

worlds = Blueprint('worlds', __name__)


@worlds.route('/worlds')
def get_worlds():
    y_list = [2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
    data = get_grade1_worlds_totals(2003, 2019)
    names, values = zip(*data[0])
    graphJSON = json.dumps([names, values], cls=plotly.utils.PlotlyJSONEncoder)
    return render_template('worlds.html',
                           graphJSON=graphJSON,
                           graph_title="Total Number of Worlds Wins in Grade {0} ({1}-{2})".format('1', 2003, 2019),
                           worlds_list=data[1], year_list=y_list)


@worlds.route('/_get_worlds_totals')
def get_worlds_total():
    grade = request.args.get('grade', '1', type=str)
    year_from = request.args.get('year_from', 2003, type=int)
    year_to = request.args.get('year_to', 2019, type=int)

    graph_title = "Total Number of Worlds Wins in Grade {0} ({1}-{2})".format(str(grade), str(year_from), str(year_to))
    data = get_worlds_data(grade, year_from, year_to)

    names, values = zip(*data[0])
    graph_data = names, values
    return {'table_data': [graph_title, data[1]], 'graph': graph_data}

templates/band_results.html
{% extends "base.html" %}

{% block content %}
    <div class="container cl-main">
        <div class="row">
            <div class="col-sm">
                <h3>Results For Each Band</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <p>Results(Wins, Piping, Drumming, Ensemble) for each band.</p>
                <p>Results for each band can be compared with the results of another band in the same grade.</p>
                <p>Please select a band from the dropdown list before pressing submit.</p>
            </div>
        </div>
        <div class="row">
            <div class="btn-toolbar" role="group">
                <div class="btn-group mr-2 flex-wrap" role="group" aria-label="First group">
                    <div class="dropdown col-sm band-dd-parent">
                      <button class="btn btn-secondary dropdown-toggle band-dd" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Chosen Grade: 1
                      </button>
                      <div id="ddselect" class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        <button value="1" class="dropdown-item" type="button">1</button>
                        <button value="2" class="dropdown-item" type="button">2</button>
                        <button value="3a" class="dropdown-item" type="button">3a</button>
                        <button value="grade" class="dropdown-item" type="button">3b</button>
                        <button value="grade" class="dropdown-item" type="button">4a</button>
                        <button value="grade" class="dropdown-item" type="button">4b</button>
                        <button value="grade" class="dropdown-item" type="button">Juv</button>
                        <button value="grade" class="dropdown-item" type="button">Nov</button>
                        <button value="grade" class="dropdown-item" type="button">Nov A</button>
                        <button value="grade" class="dropdown-item" type="button">Nov B</button>
                      </div>
                    </div>
                    <div class="dropdown col-sm band-dd-parent">
                      <button class="btn btn-secondary dropdown-toggle band-dd" type="button" id="dropdown-band" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                      <div id="band-select" class="dropdown-menu scrollable-menu">
                        <input type="text" placeholder="Search.." id="myInput" onkeyup="filterFunction()">
                      </div>
                    </div>
                    <div class="dropdown col-sm band-dd-parent" id="comp-dd">
                      <button class="btn btn-secondary dropdown-toggle band-dd" type="button" id="comp-dropdown-band" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                      <div id="comp-band-select" class="dropdown-menu scrollable-menu">
                        <input type="text" placeholder="Search.." id="comp-myInput" onkeyup="compfilterFunction()">
                      </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row band-ctrl">
            <div class="col-sm">
                <div class="btn-group mr-2" role="group" aria-label="First group">
                    <div class="dropdown col-sm band-dd-parent">
                          <button class="btn btn-secondary dropdown-toggle" type="button" id="y-from" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Year From
                          </button>
                          <div id="year-from-select" class="dropdown-menu scrollable-menu">
                                <input type="text" placeholder="Search.." id="from-input" onkeyup="fromFilterFunction()">
                                {% for i in year_list %}
                                  <button value="1" id="from-sel-button" class="dropdown-item" type="button">{{ i }}</button>
                                {% endfor %}
                          </div>
                    </div>
                    <div class="dropdown col-sm band-dd-parent">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="y-to" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Year To
                        </button>
                        <div id="year-to-select" class="dropdown-menu scrollable-menu">
                            <input type="text" placeholder="Search.." id="to-input" onkeyup="toFilterFunction()">
                            {% for i in year_list %}
                              <button value="1" id="to-sel-button" class="dropdown-item" type="button">{{ i }}</button>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row band-ctrl">
            <div class="col-sm">
                <div class="btn-group mr-2" role="group" aria-label="Last group">
                    <button id="piebar" type="button" class="btn btn-info">Pie Chart</button>
                    <button id="compare" type="button" class="btn btn-info">Comparison</button>
                    <button class="btn btn-primary" type="button" id="band-results-submit" disabled>Submit</button>
                </div>
            </div>
        </div>

        <div class="container" id="data-col">
            <div class="row">
                <div class = "col-sm">
                    <h1 id="band-name"></h1>
                </div>
            </div>
        </div>

        <div class="container chart-col">
            <div class ="row">
                <div class="col band-results-col">
                    <div id="myDiv0" class="chart"></div>
                </div>
                <div class="col band-results-col">
                    <div id="myDiv1" class="chart"></div>
                </div>
                <div class="col band-results-col">
                    <div id="myDiv2" class="chart"></div>
                </div>
                <div class="col band-results-col">
                    <div id="myDiv3" class="chart"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block pgjs %}
    <script type="text/javascript" src="{{ url_for('static',filename='js/band_results.js') }}"></script>
{% endblock %}

templates/base.html
<!doctype html>
<html>
    <head>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-145119360-1"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-145119360-1');
        </script>
        <link rel="icon" href="{{ url_for('static',filename='icons/favicon.ico') }}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles/style.css') }}">

        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.6/dist/loadingoverlay.min.js"></script>

        <title>Pipe Band Data Analysis</title>

    </head>

    <body>
        <div class ="container-fluid top-bar">
            <div class ="row tl-row-class">
                <div class="col-md-12 tl-class">
                    <a class="nav-link top-link" href="{{ url_for('dashboard.get_dashboard') }}">Pipe Band Data Analysis</a>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('dashboard.get_dashboard') }}">Dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('major_wins.get_major_wins') }}">Major Wins</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('worlds.get_worlds') }}">Worlds Results</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('band_results.get_band_results') }}">Band Results</a>
              </li>
            </ul>
          </div>
        </nav>

        {% block content %}{% endblock %}

        <div class="container">
            <footer class="cpage-footer font-small blue">
                <div class="footer-copyright text-center py-3">2019 Connor Jardine
                   <ul class="list-unstyled">
                  <li>
                    <a target="_blank" href="https://github.com/connorjardine/pipe_band_data_vis">Github Code</a>
                  </li>
                  <li>
                    <a target="_blank" href="https://www.facebook.com/connor2110">Contact</a>
                  </li>
                </ul>
              </div>
            </footer>
        </div>
    </body>

    <script>
        $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
    {% block pgjs %}{% endblock %}
</html>

templates/dashboard.html
{% extends "base.html" %}

{% block content %}
    <div class="container cl-main">
        <div class="row">
            <div class="col-sm">
                <h3>Pipe Band Results</h3>
            </div>
            <div class="col-sm"></div>
            <div class="col-sm"></div>
        </div>
        <div class="row">
            <div class="col-sm">
                <p>This site contains visualisations of Pipe Band Results for every competition from 2003 to 2019. All data
                    was collected from RSPBA Contest Summaries.</p>
                <p>The data for each subsequent year will be added to the application after all of the competitions have concluded.
                If you have any suggestions, or notice any errors please contact me either using the contact link at the bottom at
                    2188232j@student.gla.ac.uk.</p>
                <p>Note: The Worlds results are treated as two separate competitions (1MSR/1MED). As such the individual P,D, E results
                use the results from both.</p>
                <p><b>If you have pre-2003 result data please get in touch.</b></p>
            </div>
        </div>
    </div>

    <div class ="container cl-main">
        <div class="row">
            <div class="col-sm">
                <h3>Grade One Champion of Champions</h3>
            </div>
            <div class="col-sm">
                <button id="coc" class="btn btn-primary">Show/Hide</button>
            </div>
        </div>
        <div class="container" id="coc-data">
            <div class="row">
                <div class="col-sm">
                    <p>Below is a graph of the Grade One Overall and Drumming Champion of Champions table.</p>
                    <p>The graph can beswitched by pressing the button below.</p>
                </div>
            </div>
            <div class="row>">
                <div class = "col-sm">
                    <button id="ovdr" type="button" class="btn btn-primary">Drumming Champion of Champions</button>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <div id="myDiv" class="chart"></div>
                </div>
            </div>
        </div>
    </div>


    <div class="container cl-main">
        <div class = "row">
            <div class="col-sm">
                <h3>Grand Slam Winning Bands (2003-2019)</h3>
            </div>
            <div class="col-sm">
                <button id="gswb" class="btn btn-primary">Show/Hide</button>
            </div>
        </div>
        <div class="container" id="gswb-data">
            <div class="row">
                <div class="col-sm">
                    <p>
                        Below is the table of Grand Slam winning bands between 2003-2019
                    </p>
                    <table id="worlds_table" class="table table-bordered">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">Year</th>
                                <th scope="col">Grade</th>
                                <th scope="col">Grand Slam Winning Band</th>
                            </tr>
                        </thead>
                    {% for i in gs_data %}
                        <tr>
                        {% for k in i%}
                            <td>
                                {{ k }}
                            </td>
                        {% endfor %}
                        </tr>
                    {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="container cl-main">
        <div class = "row">
            <div class="col-sm">
                <h3>Perfect Scores (2003-2019)</h3>
            </div>
            <div class="col-sm">
                <button id="pswb" class="btn btn-primary">Show/Hide</button>
            </div>
        </div>

        <div class="container" id="ps1-data">
            <div class="row">
                <div class="col-sm">
                    <h5>Perfect Scores Achieved by Unique Major</h5>
                </div>
                <div class="col-sm">
                    <p>
                        Below is the table of perfect scores between 2003-2019
                    </p>
                </div>
                <div class="col-sm">
                    <button id="pswb1" class="btn btn-primary">Show/Hide</button>
                </div>
            </div>
            <div class="row">
                <div class="col-sm table-div" id="pswb1-data">
                    <table id="ps1_table" class="table table-bordered">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">Year</th>
                                <th scope="col">Competition</th>
                                <th scope="col">Grade</th>
                                <th scope="col">Band</th>
                            </tr>
                        </thead>
                    {% for i in ps_data[0] %}
                        <tr>
                        {% for k in i%}
                            <td>
                                {{ k }}
                            </td>
                        {% endfor %}
                        </tr>
                    {% endfor %}
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <h5>Highest Amount of Achieved Perfect Scores</h5>
                </div>
                <div class="col-sm">
                    <p>
                        Below is the table of total perfect scores achieved between 2003-2019
                    </p>
                </div>
                <div class="col-sm">
                    <button id="pswb2" class="btn btn-primary">Show/Hide</button>
                </div>
            </div>
            <div class="row">
                <div class="col-sm table-div" id="pswb2-data">
                    <table id="ps2_table" class="table table-bordered">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">Total</th>
                                <th scope="col">Band</th>
                            </tr>
                        </thead>
                    {% for i in ps_data[1] %}
                        <tr>
                            <td>
                                {{ i['count'] }}
                            </td>
                            <td>
                                {{ i['band_name'] }}
                            </td>
                        </tr>
                    {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block pgjs %}

    <script type="text/javascript" src="static/js/coc.js"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/dashboard.js') }}"></script>
    <script>
        create_coc_graph({{graphJSON | safe}}, {{d_graph_json | safe}});
    </script>

{% endblock %}

templates/index.html
<!doctype html>
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style type="text/css">
        .chart{
            margin-top: 30px;
            text-align: center;
        }

        .col-centered{
            float: none;
            margin: 0 auto;
        }

    </style>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('prog_coc') }}">Grade 1 Champion of Champions</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('grade') }}">Major Wins By Grade<span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="dropdown col-sm">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Choose Grade
              </button>
              <div id="ddselect" class="dropdown-menu" aria-labelledby="dropdownMenu2">
                <button value="1" class="dropdown-item" type="button">1</button>
                <button value="2" class="dropdown-item" type="button">2</button>
                <button value="3a" class="dropdown-item" type="button">3a</button>
                <button value="grade" class="dropdown-item" type="button">3b</button>
                <button value="grade" class="dropdown-item" type="button">4a</button>
                <button value="grade" class="dropdown-item" type="button">4b</button>
                <button value="grade" class="dropdown-item" type="button">Juv</button>
                <button value="grade" class="dropdown-item" type="button">Nov</button>
                <button value="grade" class="dropdown-item" type="button">Nov A</button>
                <button value="grade" class="dropdown-item" type="button">Nov B</button>
              </div>
            </div>
            <div class="col-sm">
                <button id="piebar" type="button" class="btn btn-primary">Pie Chart</button>
            </div>
            <div class="col-sm-8"></div>
        </div>
    </div>




    <div class ="container">
        <div id="myDiv" class="chart" style="height: 500px;"></div>
    <div>

</body>

    <!-- D3.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <!-- Plotly.js -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

    <script type="text/javascript">

        $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};

        var default_grade = '1';
        var graphs = {{graphJSON | safe}};
        var graph_title = "{{graph_title | safe}}";
        var state = true;

        graph_data = [{
                    x: graphs[0],
                    y: graphs[1],
                    type: 'bar'
                }];
        var bar_layout = {
            title: String(graph_title),

            xaxis: {
                tickfont: {
                    size: 14,
                    color: 'rgb(107, 107, 107)'
                }
            },
            yaxis: {
                title: 'Points Total',
                titlefont: {
                    size: 16,
                    color: 'rgb(107, 107, 107)'
                },
                tickfont: {
                    size: 14,
                    color: 'rgb(107, 107, 107)'
                }
            },
            legend: {
                x: 0,
                y: 1.0,
                bgcolor: 'rgba(255, 255, 255, 0)',
                bordercolor: 'rgba(255, 255, 255, 0)'
            },
            height: 700,
            width: 1000,
            margin: {
                l: 50,
                r: 50,
                b: 250,
                t: 50,
                pad: 4
            },

        };

        var pie_layout = {
            title: String(graph_title),
            height: 700,
            width: 1000,
            margin: {
                l: 50,
                r: 50,
                b: 250,
                t: 50,
                pad: 4
            },
        };
        Plotly.newPlot('myDiv', graph_data, bar_layout, {showSendToCloud:true});

        $('#ddselect button').on('click', function() {
            default_grade = $(this).text();

            $.getJSON($SCRIPT_ROOT + '/_get_new_title', {
                grade: String(default_grade),
                place: '1'
            }, function (data) {
                graph_title = String(data)
            });

            $.getJSON($SCRIPT_ROOT + '/_get_grade_total', {
                grade: String(default_grade),
                place: '1'
            }, function (data) {
                graphs = data;

                if(state){
                graph_data = [{
                    x: graphs[0],
                    y: graphs[1],
                    type: 'bar'
                }];
                bar_layout['title'] = graph_title;
                pie_layout['title'] = graph_title;
                Plotly.newPlot('myDiv', graph_data, bar_layout, {showSendToCloud:true});
                }
                else{
                graph_data = [{
                    labels: graphs[0],
                    values: graphs[1],
                    type: 'pie'
                }];
                bar_layout['title'] = graph_title;
                pie_layout['title'] = graph_title;
                Plotly.newPlot('myDiv', graph_data, pie_layout, {showSendToCloud:true});
            }
            });
        });

        $('#piebar').on('click', function() {
            state = !state;
            if(state){
                $("#piebar").text('Pie Chart');
                graph_data = [{
                    x: graphs[0],
                    y: graphs[1],
                    type: 'bar'
                }];
                Plotly.newPlot('myDiv', graph_data, bar_layout, {showSendToCloud:true});
            }
            else{
                $("#piebar").text('Bar Chart');
                graph_data = [{
                    labels: graphs[0],
                    values: graphs[1],
                    type: 'pie'
                }];
                Plotly.newPlot('myDiv', graph_data, pie_layout, {showSendToCloud:true});
            }

        });




    </script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</html>